---
- name: Get inventory content
  ansible.builtin.get_url:
    url: "{{ prod_base_url }}/prefixes"
    dest: "{{ pulled_inventory_location }}/inventory_acls.json"
  register: acl_content

- name: Load data
  slurp:
    src: "{{ pulled_inventory_location }}/inventory_acls.json"
  register: "prefix_json"

- name: Decode data and store as fact
  set_fact:
    prefix_json_content: "{{ prefix_json.content | b64decode }}"

- name: Register prefixes
  ansible.builtin.shell: "echo {{ item }}"
  loop: "{{ prefix_json_content.prefix }}"
  register: prefixes

- name: Create nmap inventory file
  template:
    src: "prefix_file.txt.j2"
    dest: "{{ nmap_inventory_location }}/{{ ansible_date_time.date }}.address"

- name: Create nmap working directory
  file:
    path: /etc/nmap_scan
    state: directory
    mode: '0755'

- name: Copy prefix_list file to remote server
  copy: 
    src: "{{ nmap_inventory_location }}/{{ ansible_date_time.date }}.address"
    dest: "/etc/nmap_scan/{{ ansible_date_time.date }}.address"
    mode: "0755"

- name: Install nmap
  apt:
    name: nmap

- name: Start scan
  ansible.builtin.shell: "nmap -oX /etc/nmap_scan/scan-{{ ansible_date_time.date }}.xls -iL {{ nmap_inventory_location}}/{{ ansible_date_time.date }}.address"

- name: Wait till xls file is created, so scan is completed
  ansible.builtin.wait_for:
    path: /etc/nmap_scan/scan-{{ ansible_date_time.date }}.xls
    search_regex: </nmaprun>

- name:
  debug:
    msg: "nmap -oX /etc/nmap_scan/scan-{{ ansible_date_time.date }}.xls -iL {{ nmap_inventory_location}}/{{ ansible_date_time.date }}.address"