---
- name: Remove prefix from inventory
  ansible.builtin.uri:
    url: "{{ prod_base_url }}/prefixes/remove/"
    method: POST
    return_content: yes
    body_format: json
    body: {"name" : "192.168.146.0/30"}
    status_code: 200
  register: removed_prefix