---
- name: Gather facts
  hosts: localhost
  tasks:
    - setup:


- name: Performing scan
  hosts: localhost
  become: true
  gather_facts: no
  roles:
    - scan


# - name: Inventory update
#   hosts: localhost
#   become: true
#   gather_facts: no
#   roles:
#     - inventory_update


# - name: Create ACL
#   hosts: edge_devices
#   gather_facts: false
#   roles:
#     - create_acl

