---
- name: Get inventory content
  ansible.builtin.get_url:
    url: "{{ prod_base_url }}/prefixes"
    dest: "{{ pulled_inventory_location }}/inventory_acls.json"
  register: acl_content

- name: print if changed
  debug:
    msg: "valtozott"
  when: acl_content.changed
  
- name: Display the JSON file content
  shell: cat {{ pulled_inventory_location }}/inventory_acls.json
  register: acl_result

- name: save the Json data to a Variable as a Fact
  set_fact:
    jsondata: "{{ acl_result.stdout | from_json }}"

- name: Create master iACL config file from inventory
  template:
    src: acl_rule.j2
    dest: "{{ generated_acl_location }}/acl_rule.cfg"

- name: Configure iACL group on edge device
  cisco.ios.ios_command:
    commands:
      - configure terminal
      - ip access-list extended iACL
      - "deny tcp any {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }}" ## nem fogja felvenni újra ha már létezik
      - "deny udp any {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }}"
      - "deny tcp {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }} any"
      - "deny udp {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }} any"
      - end
  loop: "{{ jsondata.prefix }}"

