---
- name: Create master iACL config file from inventory
  template:
    src: acl_rule.j2
    dest: "{{ generated_acl_location }}/acl_rule.cfg"
  when: hostvars.localhost.acl_content.changed

- name: Configure iACL group on edge device
  cisco.ios.ios_command:
    commands:
      - configure terminal
      - ip access-list extended iACL
      - "deny tcp any {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }}" ## nem fogja felvenni újra ha már létezik
      - "deny udp any {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }}"
      - "deny tcp {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }} any"
      - "deny udp {{ item | split('/') | first }} {{ item | ipaddr('hostmask') }} any"
      - end
  loop: "{{ hostvars.localhost.jsondata.prefix }}"
  when: hostvars.localhost.acl_content.changed

- name: save running to startup when modified
  cisco.ios.ios_config:
    save_when: always
  when: hostvars.localhost.acl_content.changed