---
- name: Get inventory content
  ansible.builtin.get_url:
    url: "{{ prod_base_url }}/prefixes"
    dest: "{{ pulled_inventory_location }}/inventory_acls.json"
  register: acl_content

- name: Set as fact
  set_fact:
    jsondata: "{{lookup('ansible.builtin.file', '{{ pulled_inventory_location }}/inventory_acls.json') }}"

- ansible.builtin.debug:
    msg: "{{ jsondata }}"